#!/bin/sh

if [ "$(basename -- "$0")" == "$(basename -- "$BASH_SOURCE")" ]; then
  echo "Don't run $0, source it" >&2
  echo "source `basename $BASH_SOURCE` in directory $dir"
  exit 1
fi

if [ "$(dirname -- "$(realpath $BASH_SOURCE)")" != "$PWD" ]; then
  echo "FAIL: source `basename $BASH_SOURCE` in directory $dir"
  return
fi

export PIN_HOME=${PWD}/pin
export PIN=${PIN_HOME}/intel64/bin/pinbin
export MCSIM_PARENT_DIR=${PWD}
export PINTOOL=${MCSIM_PARENT_DIR}/Pthread/mypthreadtool
export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=${PIN_HOME}/intel64/lib-ext:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=${MCSIM_PARENT_DIR}/Apps/hooks/lib:$LD_LIBRARY_PATH
