#ifndef __INS_CATEGORY_ENUM_H__
#define __INS_CATEGORY_ENUM_H__

typedef enum {
  ART_CATEGORY_START = XED_CATEGORY_LAST + 1,
  ART_CATEGORY_GET = ART_CATEGORY_START,
  ART_CATEGORY_ADD,
  ART_CATEGORY_MULT,
  ART_CATEGORY_DOT,
  PEI_CATEGORY_DOT,
  PEI_CATEGORY_ATOMIC,
  ART_CATEGORY_LAST
} ins_category_enum_t;

#endif
