##################################################################################
#  CasHMC v1.2 - 2016.09.27
#  A Cycle-accurate Simulator for Hybrid Memory Cube
#
#  Copyright (c) 2016, Dong-Ik Jeon
#                      Ki-Seok Chung
#                      Hanyang University
#                      estwings57 [at] gmail [dot] com
#  All rights reserved.
##################################################################################

default: all

CXXFLAGS=-O3 -g -DDEBUG_LOG
#DFLAGS=-DDEBUG_FLOW_CONTROL -DDEBUG_GATHER
#DFLAGS=-DDEBUG_UPDATE -DCOMPUTE -DDEBUG_GATHER
##DFLAGS+= -DDEBUG_ROUTING
#DFLAGS+= -DCASHMC
CXXFLAGS+=$(DFLAGS)
EXE_NAME=CasHMC
#SRCDIR=sources
SRCDIR=
OBJDIR=obj
DEPDIR=dep

#SRC = $(wildcard $(SRCDIR)/*.cpp)
SRC = $(wildcard *.cpp)

OBJ = $(subst LibraryStubs.o,,$(addprefix $(OBJDIR)/,$(addsuffix .o, $(basename $(SRC)))))

REBUILDABLES=$(OBJ) $(EXE_NAME)

all: ${OBJ}

#   $@ target name, $^ target deps, $< matched pattern
#$(EXE_NAME): $(OBJ)
#	$(CXX) $(LINK_FLAGS) -o $@ $^ 
#	@echo "Built $@ successfully" 

#include the autogenerated dependency files for each .o file
-include $(OBJ:.o=.dep)

# build dependency list via gcc -M and save to a .dep file
$(DEPDIR)/%.dep : %.cpp
	@$(CXX) -M $(CXXFLAGS) $< > $@

# build all .cpp files to .o files
$(OBJDIR)/%.o : %.cpp
	g++ $(CXXFLAGS) -o $@ -c $<

clean: 
	-rm -f ${REBUILDABLES} $(SRCDIR)/*.dep -r obj
